---
  engines:
    eslint:
      enabled: true
      channel: "eslint-3"
    nodesecurity:
      enabled: true
    fixme:
      enabled: true
    duplication:
      enabled: true
      config:
        languages:
        - javascript
  ratings:
    paths:
    - "**.js"
